---
name: IO-NestedCapture
version: 1.03
author:
  - 'Andrew Sterling Hanenkamp, E<lt>hanenkamp@cpan.orgE<gt>'
abstract: module for performing nested STD* handle captures
license: perl
provides:
  IO::NestedCapture:
    file: lib/IO/NestedCapture.pm
    version: 1.03
generated_by: Module::Build version 0.2611
