---
name: IO-NestedCapture
version: 1.01
author:
  - 'Andrew Sterling Hanenkamp, E<lt>hanenkamp@cpan.orgE<gt>'
abstract: module for performing nasted STD* handle captures
license: perl
provides:
  IO::NestedCapture:
    file: lib/IO/NestedCapture.pm
    version: 1.01
generated_by: Module::Build version 0.2611
